source 'https://rubygems.org'

# Language Operator SDK - installed in base image and available at /language-operator
gem 'language-operator', '0.1.0', path: '/language-operator'

group :development, :test do
  gem 'rspec', '~> 3.13'
  gem 'webmock', '~> 3.23'
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-performance', '~> 1.20'
  gem 'yard', '~> 0.9.37'
end
