source 'https://rubygems.org'

gem 'mcp', '~> 0.4.0'
gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'rackup', '~> 2.1'
gem 'puma', '~> 6.4'
gem 'json', '~> 2.7'

group :development do
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-performance', '~> 1.20'
  gem 'yard', '~> 0.9.37'
  # rdoc omitted - causes build issues on NixOS due to psych native extension
  # The warning about rdoc is harmless and only affects Ruby 3.5+
end
