apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - languagepersona.project-manager.yaml
  - languagepersona.engineer.yaml
  - languageagent.supervisor.yaml
  - languageagent.worker-0.yaml
  - languageagent.worker-1.yaml
  - languageagent.worker-2.yaml
