# frozen_string_literal: true

source 'https://rubygems.org'

# Private gem registry for language-operator SDK
source 'https://git.theryans.io/api/packages/language-operator/rubygems' do
  gem 'language-operator', '~> 0.1.15'
end

# Web server dependencies
gem 'rack', '~> 3.0'
gem 'webrick', '~> 1.8'

# JSON handling (included in Ruby stdlib but explicit for clarity)
gem 'json', '~> 2.7'

group :development do
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-performance', '~> 1.20'
  gem 'yard', '~> 0.9.37'
end
