{{- if .Values.agentRBAC.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "language-operator.fullname" . }}-agents
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "language-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "language-operator.fullname" . }}-agents
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
{{- end }}