AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'vendor/**/*'
    - 'doc/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 55

Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Max: 65

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 16

Metrics/BlockLength:
  Max: 30
