source 'https://rubygems.org'

# Use langop gem for DSL functionality
# The gem is pre-installed in the langop/ruby base image
# gem 'aictl' is already available globally

# Tool server dependencies
gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'rackup', '~> 2.1'
gem 'puma', '~> 6.4'
gem 'json', '~> 2.7'

group :development do
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-performance', '~> 1.20'
  gem 'yard', '~> 0.9.37'
  # rdoc omitted - causes build issues on NixOS due to psych native extension
  # The warning about rdoc is harmless and only affects Ruby 3.5+
end
