# frozen_string_literal: true

source 'https://rubygems.org'
source 'https://git.theryans.io/api/packages/language-operator/rubygems'

# Language Operator SDK (includes ruby_llm, ruby_llm-mcp, etc.)
gem 'language-operator', '~> 0.1.0'

group :development do
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-performance', '~> 1.20'
  gem 'yard', '~> 0.9.37'
end
