//go:build !ignore_autogenerated

/*
Copyright 2025 Langop Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentContentFilterSpec) DeepCopyInto(out *AgentContentFilterSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentContentFilterSpec.
func (in *AgentContentFilterSpec) DeepCopy() *AgentContentFilterSpec {
	if in == nil {
		return nil
	}
	out := new(AgentContentFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCostMetrics) DeepCopyInto(out *AgentCostMetrics) {
	*out = *in
	if in.TotalCost != nil {
		in, out := &in.TotalCost, &out.TotalCost
		*out = new(float64)
		**out = **in
	}
	if in.ModelCosts != nil {
		in, out := &in.ModelCosts, &out.ModelCosts
		*out = make([]ModelCostSpec, len(*in))
		copy(*out, *in)
	}
	if in.LastReset != nil {
		in, out := &in.LastReset, &out.LastReset
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCostMetrics.
func (in *AgentCostMetrics) DeepCopy() *AgentCostMetrics {
	if in == nil {
		return nil
	}
	out := new(AgentCostMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMetrics) DeepCopyInto(out *AgentMetrics) {
	*out = *in
	if in.AverageIterations != nil {
		in, out := &in.AverageIterations, &out.AverageIterations
		*out = new(float64)
		**out = **in
	}
	if in.AverageExecutionTime != nil {
		in, out := &in.AverageExecutionTime, &out.AverageExecutionTime
		*out = new(float64)
		**out = **in
	}
	if in.SuccessRate != nil {
		in, out := &in.SuccessRate, &out.SuccessRate
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentMetrics.
func (in *AgentMetrics) DeepCopy() *AgentMetrics {
	if in == nil {
		return nil
	}
	out := new(AgentMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentObservabilitySpec) DeepCopyInto(out *AgentObservabilitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentObservabilitySpec.
func (in *AgentObservabilitySpec) DeepCopy() *AgentObservabilitySpec {
	if in == nil {
		return nil
	}
	out := new(AgentObservabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentRateLimitSpec) DeepCopyInto(out *AgentRateLimitSpec) {
	*out = *in
	if in.RequestsPerMinute != nil {
		in, out := &in.RequestsPerMinute, &out.RequestsPerMinute
		*out = new(int32)
		**out = **in
	}
	if in.TokensPerMinute != nil {
		in, out := &in.TokensPerMinute, &out.TokensPerMinute
		*out = new(int32)
		**out = **in
	}
	if in.ToolCallsPerMinute != nil {
		in, out := &in.ToolCallsPerMinute, &out.ToolCallsPerMinute
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentRateLimitSpec.
func (in *AgentRateLimitSpec) DeepCopy() *AgentRateLimitSpec {
	if in == nil {
		return nil
	}
	out := new(AgentRateLimitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CachingSpec) DeepCopyInto(out *CachingSpec) {
	*out = *in
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CachingSpec.
func (in *CachingSpec) DeepCopy() *CachingSpec {
	if in == nil {
		return nil
	}
	out := new(CachingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertIssuerReference) DeepCopyInto(out *CertIssuerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertIssuerReference.
func (in *CertIssuerReference) DeepCopy() *CertIssuerReference {
	if in == nil {
		return nil
	}
	out := new(CertIssuerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostMetrics) DeepCopyInto(out *CostMetrics) {
	*out = *in
	if in.TotalCost != nil {
		in, out := &in.TotalCost, &out.TotalCost
		*out = new(float64)
		**out = **in
	}
	if in.InputTokenCost != nil {
		in, out := &in.InputTokenCost, &out.InputTokenCost
		*out = new(float64)
		**out = **in
	}
	if in.OutputTokenCost != nil {
		in, out := &in.OutputTokenCost, &out.OutputTokenCost
		*out = new(float64)
		**out = **in
	}
	if in.LastReset != nil {
		in, out := &in.LastReset, &out.LastReset
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostMetrics.
func (in *CostMetrics) DeepCopy() *CostMetrics {
	if in == nil {
		return nil
	}
	out := new(CostMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostTrackingSpec) DeepCopyInto(out *CostTrackingSpec) {
	*out = *in
	if in.InputTokenCost != nil {
		in, out := &in.InputTokenCost, &out.InputTokenCost
		*out = new(float64)
		**out = **in
	}
	if in.OutputTokenCost != nil {
		in, out := &in.OutputTokenCost, &out.OutputTokenCost
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostTrackingSpec.
func (in *CostTrackingSpec) DeepCopy() *CostTrackingSpec {
	if in == nil {
		return nil
	}
	out := new(CostTrackingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSpec) DeepCopyInto(out *EndpointSpec) {
	*out = *in
	if in.Weight != nil {
		in, out := &in.Weight, &out.Weight
		*out = new(int32)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSpec.
func (in *EndpointSpec) DeepCopy() *EndpointSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointStatusSpec) DeepCopyInto(out *EndpointStatusSpec) {
	*out = *in
	if in.LastCheck != nil {
		in, out := &in.LastCheck, &out.LastCheck
		*out = (*in).DeepCopy()
	}
	if in.Latency != nil {
		in, out := &in.Latency, &out.Latency
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointStatusSpec.
func (in *EndpointStatusSpec) DeepCopy() *EndpointStatusSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventTriggerSpec) DeepCopyInto(out *EventTriggerSpec) {
	*out = *in
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventTriggerSpec.
func (in *EventTriggerSpec) DeepCopy() *EventTriggerSpec {
	if in == nil {
		return nil
	}
	out := new(EventTriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckSpec) DeepCopyInto(out *HealthCheckSpec) {
	*out = *in
	if in.UnhealthyThreshold != nil {
		in, out := &in.UnhealthyThreshold, &out.UnhealthyThreshold
		*out = new(int32)
		**out = **in
	}
	if in.HealthyThreshold != nil {
		in, out := &in.HealthyThreshold, &out.HealthyThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckSpec.
func (in *HealthCheckSpec) DeepCopy() *HealthCheckSpec {
	if in == nil {
		return nil
	}
	out := new(HealthCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressConfig) DeepCopyInto(out *IngressConfig) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(IngressTLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressConfig.
func (in *IngressConfig) DeepCopy() *IngressConfig {
	if in == nil {
		return nil
	}
	out := new(IngressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressTLSConfig) DeepCopyInto(out *IngressTLSConfig) {
	*out = *in
	if in.IssuerRef != nil {
		in, out := &in.IssuerRef, &out.IssuerRef
		*out = new(CertIssuerReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressTLSConfig.
func (in *IngressTLSConfig) DeepCopy() *IngressTLSConfig {
	if in == nil {
		return nil
	}
	out := new(IngressTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeSourceSpec) DeepCopyInto(out *KnowledgeSourceSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeSourceSpec.
func (in *KnowledgeSourceSpec) DeepCopy() *KnowledgeSourceSpec {
	if in == nil {
		return nil
	}
	out := new(KnowledgeSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageAgent) DeepCopyInto(out *LanguageAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageAgent.
func (in *LanguageAgent) DeepCopy() *LanguageAgent {
	if in == nil {
		return nil
	}
	out := new(LanguageAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LanguageAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageAgentList) DeepCopyInto(out *LanguageAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LanguageAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageAgentList.
func (in *LanguageAgentList) DeepCopy() *LanguageAgentList {
	if in == nil {
		return nil
	}
	out := new(LanguageAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LanguageAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageAgentSpec) DeepCopyInto(out *LanguageAgentSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.ModelRefs != nil {
		in, out := &in.ModelRefs, &out.ModelRefs
		*out = make([]ModelReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ToolRefs != nil {
		in, out := &in.ToolRefs, &out.ToolRefs
		*out = make([]ToolReference, len(*in))
		copy(*out, *in)
	}
	if in.PersonaRefs != nil {
		in, out := &in.PersonaRefs, &out.PersonaRefs
		*out = make([]PersonaReference, len(*in))
		copy(*out, *in)
	}
	if in.EventTriggers != nil {
		in, out := &in.EventTriggers, &out.EventTriggers
		*out = make([]EventTriggerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaxIterations != nil {
		in, out := &in.MaxIterations, &out.MaxIterations
		*out = new(int32)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.BackoffLimit != nil {
		in, out := &in.BackoffLimit, &out.BackoffLimit
		*out = new(int32)
		**out = **in
	}
	if in.MemoryStore != nil {
		in, out := &in.MemoryStore, &out.MemoryStore
		*out = new(MemoryStoreSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(AgentObservabilitySpec)
		**out = **in
	}
	if in.RateLimits != nil {
		in, out := &in.RateLimits, &out.RateLimits
		*out = new(AgentRateLimitSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SafetyConfig != nil {
		in, out := &in.SafetyConfig, &out.SafetyConfig
		*out = new(SafetyConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Workspace != nil {
		in, out := &in.Workspace, &out.Workspace
		*out = new(WorkspaceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]NetworkRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageAgentSpec.
func (in *LanguageAgentSpec) DeepCopy() *LanguageAgentSpec {
	if in == nil {
		return nil
	}
	out := new(LanguageAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageAgentStatus) DeepCopyInto(out *LanguageAgentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastExecutionTime != nil {
		in, out := &in.LastExecutionTime, &out.LastExecutionTime
		*out = (*in).DeepCopy()
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(AgentMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.ToolUsage != nil {
		in, out := &in.ToolUsage, &out.ToolUsage
		*out = make([]ToolUsageSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ModelUsage != nil {
		in, out := &in.ModelUsage, &out.ModelUsage
		*out = make([]ModelUsageSpec, len(*in))
		copy(*out, *in)
	}
	if in.CostMetrics != nil {
		in, out := &in.CostMetrics, &out.CostMetrics
		*out = new(AgentCostMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.SynthesisInfo != nil {
		in, out := &in.SynthesisInfo, &out.SynthesisInfo
		*out = new(SynthesisInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.WebhookURLs != nil {
		in, out := &in.WebhookURLs, &out.WebhookURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RuntimeErrors != nil {
		in, out := &in.RuntimeErrors, &out.RuntimeErrors
		*out = make([]RuntimeError, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageAgentStatus.
func (in *LanguageAgentStatus) DeepCopy() *LanguageAgentStatus {
	if in == nil {
		return nil
	}
	out := new(LanguageAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageCluster) DeepCopyInto(out *LanguageCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageCluster.
func (in *LanguageCluster) DeepCopy() *LanguageCluster {
	if in == nil {
		return nil
	}
	out := new(LanguageCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LanguageCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageClusterList) DeepCopyInto(out *LanguageClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LanguageCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageClusterList.
func (in *LanguageClusterList) DeepCopy() *LanguageClusterList {
	if in == nil {
		return nil
	}
	out := new(LanguageClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LanguageClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageClusterSpec) DeepCopyInto(out *LanguageClusterSpec) {
	*out = *in
	if in.IngressConfig != nil {
		in, out := &in.IngressConfig, &out.IngressConfig
		*out = new(IngressConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageClusterSpec.
func (in *LanguageClusterSpec) DeepCopy() *LanguageClusterSpec {
	if in == nil {
		return nil
	}
	out := new(LanguageClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageClusterStatus) DeepCopyInto(out *LanguageClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageClusterStatus.
func (in *LanguageClusterStatus) DeepCopy() *LanguageClusterStatus {
	if in == nil {
		return nil
	}
	out := new(LanguageClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageModel) DeepCopyInto(out *LanguageModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageModel.
func (in *LanguageModel) DeepCopy() *LanguageModel {
	if in == nil {
		return nil
	}
	out := new(LanguageModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LanguageModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageModelList) DeepCopyInto(out *LanguageModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LanguageModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageModelList.
func (in *LanguageModelList) DeepCopy() *LanguageModelList {
	if in == nil {
		return nil
	}
	out := new(LanguageModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LanguageModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageModelSpec) DeepCopyInto(out *LanguageModelSpec) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(ProviderConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimits != nil {
		in, out := &in.RateLimits, &out.RateLimits
		*out = new(RateLimitSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RetryPolicy != nil {
		in, out := &in.RetryPolicy, &out.RetryPolicy
		*out = new(RetryPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Fallbacks != nil {
		in, out := &in.Fallbacks, &out.Fallbacks
		*out = make([]ModelFallbackSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoadBalancing != nil {
		in, out := &in.LoadBalancing, &out.LoadBalancing
		*out = new(LoadBalancingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Caching != nil {
		in, out := &in.Caching, &out.Caching
		*out = new(CachingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(ObservabilitySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CostTracking != nil {
		in, out := &in.CostTracking, &out.CostTracking
		*out = new(CostTrackingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]RegionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]NetworkRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageModelSpec.
func (in *LanguageModelSpec) DeepCopy() *LanguageModelSpec {
	if in == nil {
		return nil
	}
	out := new(LanguageModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageModelStatus) DeepCopyInto(out *LanguageModelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastHealthCheck != nil {
		in, out := &in.LastHealthCheck, &out.LastHealthCheck
		*out = (*in).DeepCopy()
	}
	if in.EndpointStatus != nil {
		in, out := &in.EndpointStatus, &out.EndpointStatus
		*out = make([]EndpointStatusSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RegionStatus != nil {
		in, out := &in.RegionStatus, &out.RegionStatus
		*out = make([]RegionStatusSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(ModelMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.CostMetrics != nil {
		in, out := &in.CostMetrics, &out.CostMetrics
		*out = new(CostMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageModelStatus.
func (in *LanguageModelStatus) DeepCopy() *LanguageModelStatus {
	if in == nil {
		return nil
	}
	out := new(LanguageModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguagePersona) DeepCopyInto(out *LanguagePersona) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguagePersona.
func (in *LanguagePersona) DeepCopy() *LanguagePersona {
	if in == nil {
		return nil
	}
	out := new(LanguagePersona)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LanguagePersona) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguagePersonaList) DeepCopyInto(out *LanguagePersonaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LanguagePersona, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguagePersonaList.
func (in *LanguagePersonaList) DeepCopy() *LanguagePersonaList {
	if in == nil {
		return nil
	}
	out := new(LanguagePersonaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LanguagePersonaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguagePersonaSpec) DeepCopyInto(out *LanguagePersonaSpec) {
	*out = *in
	if in.Instructions != nil {
		in, out := &in.Instructions, &out.Instructions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]PersonaRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Examples != nil {
		in, out := &in.Examples, &out.Examples
		*out = make([]PersonaExample, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Limitations != nil {
		in, out := &in.Limitations, &out.Limitations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResponseFormat != nil {
		in, out := &in.ResponseFormat, &out.ResponseFormat
		*out = new(ResponseFormatSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ToolPreferences != nil {
		in, out := &in.ToolPreferences, &out.ToolPreferences
		*out = new(ToolPreferencesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.KnowledgeSources != nil {
		in, out := &in.KnowledgeSources, &out.KnowledgeSources
		*out = make([]KnowledgeSourceSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Constraints != nil {
		in, out := &in.Constraints, &out.Constraints
		*out = new(PersonaConstraints)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ParentPersona != nil {
		in, out := &in.ParentPersona, &out.ParentPersona
		*out = new(PersonaReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguagePersonaSpec.
func (in *LanguagePersonaSpec) DeepCopy() *LanguagePersonaSpec {
	if in == nil {
		return nil
	}
	out := new(LanguagePersonaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguagePersonaStatus) DeepCopyInto(out *LanguagePersonaStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveAgents != nil {
		in, out := &in.ActiveAgents, &out.ActiveAgents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ValidationResult != nil {
		in, out := &in.ValidationResult, &out.ValidationResult
		*out = new(PersonaValidation)
		(*in).DeepCopyInto(*out)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(PersonaMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguagePersonaStatus.
func (in *LanguagePersonaStatus) DeepCopy() *LanguagePersonaStatus {
	if in == nil {
		return nil
	}
	out := new(LanguagePersonaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageTool) DeepCopyInto(out *LanguageTool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageTool.
func (in *LanguageTool) DeepCopy() *LanguageTool {
	if in == nil {
		return nil
	}
	out := new(LanguageTool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LanguageTool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageToolList) DeepCopyInto(out *LanguageToolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LanguageTool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageToolList.
func (in *LanguageToolList) DeepCopy() *LanguageToolList {
	if in == nil {
		return nil
	}
	out := new(LanguageToolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LanguageToolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageToolSpec) DeepCopyInto(out *LanguageToolSpec) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]v1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]v1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAnnotations != nil {
		in, out := &in.ServiceAnnotations, &out.ServiceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(PodDisruptionBudgetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdateStrategy != nil {
		in, out := &in.UpdateStrategy, &out.UpdateStrategy
		*out = new(UpdateStrategySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]NetworkRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageToolSpec.
func (in *LanguageToolSpec) DeepCopy() *LanguageToolSpec {
	if in == nil {
		return nil
	}
	out := new(LanguageToolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LanguageToolStatus) DeepCopyInto(out *LanguageToolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AvailableTools != nil {
		in, out := &in.AvailableTools, &out.AvailableTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ToolSchemas != nil {
		in, out := &in.ToolSchemas, &out.ToolSchemas
		*out = make([]ToolSchema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LanguageToolStatus.
func (in *LanguageToolStatus) DeepCopy() *LanguageToolStatus {
	if in == nil {
		return nil
	}
	out := new(LanguageToolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancingSpec) DeepCopyInto(out *LoadBalancingSpec) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]EndpointSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(HealthCheckSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancingSpec.
func (in *LoadBalancingSpec) DeepCopy() *LoadBalancingSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStoreSpec) DeepCopyInto(out *MemoryStoreSpec) {
	*out = *in
	if in.ConnectionSecretRef != nil {
		in, out := &in.ConnectionSecretRef, &out.ConnectionSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.RetentionPolicy != nil {
		in, out := &in.RetentionPolicy, &out.RetentionPolicy
		*out = new(RetentionPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxConversations != nil {
		in, out := &in.MaxConversations, &out.MaxConversations
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStoreSpec.
func (in *MemoryStoreSpec) DeepCopy() *MemoryStoreSpec {
	if in == nil {
		return nil
	}
	out := new(MemoryStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelCostSpec) DeepCopyInto(out *ModelCostSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelCostSpec.
func (in *ModelCostSpec) DeepCopy() *ModelCostSpec {
	if in == nil {
		return nil
	}
	out := new(ModelCostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelFallbackSpec) DeepCopyInto(out *ModelFallbackSpec) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelFallbackSpec.
func (in *ModelFallbackSpec) DeepCopy() *ModelFallbackSpec {
	if in == nil {
		return nil
	}
	out := new(ModelFallbackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelLoggingSpec) DeepCopyInto(out *ModelLoggingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelLoggingSpec.
func (in *ModelLoggingSpec) DeepCopy() *ModelLoggingSpec {
	if in == nil {
		return nil
	}
	out := new(ModelLoggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMetrics) DeepCopyInto(out *ModelMetrics) {
	*out = *in
	if in.AverageLatency != nil {
		in, out := &in.AverageLatency, &out.AverageLatency
		*out = new(int32)
		**out = **in
	}
	if in.P95Latency != nil {
		in, out := &in.P95Latency, &out.P95Latency
		*out = new(int32)
		**out = **in
	}
	if in.P99Latency != nil {
		in, out := &in.P99Latency, &out.P99Latency
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMetrics.
func (in *ModelMetrics) DeepCopy() *ModelMetrics {
	if in == nil {
		return nil
	}
	out := new(ModelMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelReference) DeepCopyInto(out *ModelReference) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelReference.
func (in *ModelReference) DeepCopy() *ModelReference {
	if in == nil {
		return nil
	}
	out := new(ModelReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelUsageSpec) DeepCopyInto(out *ModelUsageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelUsageSpec.
func (in *ModelUsageSpec) DeepCopy() *ModelUsageSpec {
	if in == nil {
		return nil
	}
	out := new(ModelUsageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPeer) DeepCopyInto(out *NetworkPeer) {
	*out = *in
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceReference)
		**out = **in
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPeer.
func (in *NetworkPeer) DeepCopy() *NetworkPeer {
	if in == nil {
		return nil
	}
	out := new(NetworkPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPort) DeepCopyInto(out *NetworkPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPort.
func (in *NetworkPort) DeepCopy() *NetworkPort {
	if in == nil {
		return nil
	}
	out := new(NetworkPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRule) DeepCopyInto(out *NetworkRule) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = new(NetworkPeer)
		(*in).DeepCopyInto(*out)
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = new(NetworkPeer)
		(*in).DeepCopyInto(*out)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]NetworkPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRule.
func (in *NetworkRule) DeepCopy() *NetworkRule {
	if in == nil {
		return nil
	}
	out := new(NetworkRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilitySpec) DeepCopyInto(out *ObservabilitySpec) {
	*out = *in
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(ModelLoggingSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilitySpec.
func (in *ObservabilitySpec) DeepCopy() *ObservabilitySpec {
	if in == nil {
		return nil
	}
	out := new(ObservabilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonaConstraints) DeepCopyInto(out *PersonaConstraints) {
	*out = *in
	if in.MaxResponseTokens != nil {
		in, out := &in.MaxResponseTokens, &out.MaxResponseTokens
		*out = new(int32)
		**out = **in
	}
	if in.MaxToolCalls != nil {
		in, out := &in.MaxToolCalls, &out.MaxToolCalls
		*out = new(int32)
		**out = **in
	}
	if in.MaxKnowledgeQueries != nil {
		in, out := &in.MaxKnowledgeQueries, &out.MaxKnowledgeQueries
		*out = new(int32)
		**out = **in
	}
	if in.BlockedTopics != nil {
		in, out := &in.BlockedTopics, &out.BlockedTopics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedDomains != nil {
		in, out := &in.AllowedDomains, &out.AllowedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonaConstraints.
func (in *PersonaConstraints) DeepCopy() *PersonaConstraints {
	if in == nil {
		return nil
	}
	out := new(PersonaConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonaExample) DeepCopyInto(out *PersonaExample) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonaExample.
func (in *PersonaExample) DeepCopy() *PersonaExample {
	if in == nil {
		return nil
	}
	out := new(PersonaExample)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonaMetrics) DeepCopyInto(out *PersonaMetrics) {
	*out = *in
	if in.AverageResponseLength != nil {
		in, out := &in.AverageResponseLength, &out.AverageResponseLength
		*out = new(int32)
		**out = **in
	}
	if in.AverageToolCalls != nil {
		in, out := &in.AverageToolCalls, &out.AverageToolCalls
		*out = new(float64)
		**out = **in
	}
	if in.RuleActivations != nil {
		in, out := &in.RuleActivations, &out.RuleActivations
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TopTools != nil {
		in, out := &in.TopTools, &out.TopTools
		*out = make([]ToolFrequency, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopTopics != nil {
		in, out := &in.TopTopics, &out.TopTopics
		*out = make([]TopicFrequency, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UserSatisfaction != nil {
		in, out := &in.UserSatisfaction, &out.UserSatisfaction
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonaMetrics.
func (in *PersonaMetrics) DeepCopy() *PersonaMetrics {
	if in == nil {
		return nil
	}
	out := new(PersonaMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonaReference) DeepCopyInto(out *PersonaReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonaReference.
func (in *PersonaReference) DeepCopy() *PersonaReference {
	if in == nil {
		return nil
	}
	out := new(PersonaReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonaRule) DeepCopyInto(out *PersonaRule) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonaRule.
func (in *PersonaRule) DeepCopy() *PersonaRule {
	if in == nil {
		return nil
	}
	out := new(PersonaRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersonaValidation) DeepCopyInto(out *PersonaValidation) {
	*out = *in
	if in.ValidationTime != nil {
		in, out := &in.ValidationTime, &out.ValidationTime
		*out = (*in).DeepCopy()
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Score != nil {
		in, out := &in.Score, &out.Score
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersonaValidation.
func (in *PersonaValidation) DeepCopy() *PersonaValidation {
	if in == nil {
		return nil
	}
	out := new(PersonaValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDisruptionBudgetSpec) DeepCopyInto(out *PodDisruptionBudgetSpec) {
	*out = *in
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(int32)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDisruptionBudgetSpec.
func (in *PodDisruptionBudgetSpec) DeepCopy() *PodDisruptionBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(PodDisruptionBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfiguration) DeepCopyInto(out *ProviderConfiguration) {
	*out = *in
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int32)
		**out = **in
	}
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(float64)
		**out = **in
	}
	if in.TopP != nil {
		in, out := &in.TopP, &out.TopP
		*out = new(float64)
		**out = **in
	}
	if in.FrequencyPenalty != nil {
		in, out := &in.FrequencyPenalty, &out.FrequencyPenalty
		*out = new(float64)
		**out = **in
	}
	if in.PresencePenalty != nil {
		in, out := &in.PresencePenalty, &out.PresencePenalty
		*out = new(float64)
		**out = **in
	}
	if in.StopSequences != nil {
		in, out := &in.StopSequences, &out.StopSequences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalParameters != nil {
		in, out := &in.AdditionalParameters, &out.AdditionalParameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfiguration.
func (in *ProviderConfiguration) DeepCopy() *ProviderConfiguration {
	if in == nil {
		return nil
	}
	out := new(ProviderConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitSpec) DeepCopyInto(out *RateLimitSpec) {
	*out = *in
	if in.RequestsPerMinute != nil {
		in, out := &in.RequestsPerMinute, &out.RequestsPerMinute
		*out = new(int32)
		**out = **in
	}
	if in.TokensPerMinute != nil {
		in, out := &in.TokensPerMinute, &out.TokensPerMinute
		*out = new(int32)
		**out = **in
	}
	if in.ConcurrentRequests != nil {
		in, out := &in.ConcurrentRequests, &out.ConcurrentRequests
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitSpec.
func (in *RateLimitSpec) DeepCopy() *RateLimitSpec {
	if in == nil {
		return nil
	}
	out := new(RateLimitSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionSpec) DeepCopyInto(out *RegionSpec) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionSpec.
func (in *RegionSpec) DeepCopy() *RegionSpec {
	if in == nil {
		return nil
	}
	out := new(RegionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionStatusSpec) DeepCopyInto(out *RegionStatusSpec) {
	*out = *in
	if in.Latency != nil {
		in, out := &in.Latency, &out.Latency
		*out = new(int32)
		**out = **in
	}
	if in.LastCheck != nil {
		in, out := &in.LastCheck, &out.LastCheck
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionStatusSpec.
func (in *RegionStatusSpec) DeepCopy() *RegionStatusSpec {
	if in == nil {
		return nil
	}
	out := new(RegionStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseFormatSpec) DeepCopyInto(out *ResponseFormatSpec) {
	*out = *in
	if in.MaxLength != nil {
		in, out := &in.MaxLength, &out.MaxLength
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseFormatSpec.
func (in *ResponseFormatSpec) DeepCopy() *ResponseFormatSpec {
	if in == nil {
		return nil
	}
	out := new(ResponseFormatSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicySpec) DeepCopyInto(out *RetentionPolicySpec) {
	*out = *in
	if in.MaxMessages != nil {
		in, out := &in.MaxMessages, &out.MaxMessages
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicySpec.
func (in *RetentionPolicySpec) DeepCopy() *RetentionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryPolicySpec) DeepCopyInto(out *RetryPolicySpec) {
	*out = *in
	if in.MaxAttempts != nil {
		in, out := &in.MaxAttempts, &out.MaxAttempts
		*out = new(int32)
		**out = **in
	}
	if in.BackoffMultiplier != nil {
		in, out := &in.BackoffMultiplier, &out.BackoffMultiplier
		*out = new(float64)
		**out = **in
	}
	if in.RetryableStatusCodes != nil {
		in, out := &in.RetryableStatusCodes, &out.RetryableStatusCodes
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryPolicySpec.
func (in *RetryPolicySpec) DeepCopy() *RetryPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RetryPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateSpec) DeepCopyInto(out *RollingUpdateSpec) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(int32)
		**out = **in
	}
	if in.MaxSurge != nil {
		in, out := &in.MaxSurge, &out.MaxSurge
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateSpec.
func (in *RollingUpdateSpec) DeepCopy() *RollingUpdateSpec {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeError) DeepCopyInto(out *RuntimeError) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.StackTrace != nil {
		in, out := &in.StackTrace, &out.StackTrace
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeError.
func (in *RuntimeError) DeepCopy() *RuntimeError {
	if in == nil {
		return nil
	}
	out := new(RuntimeError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetyConfigSpec) DeepCopyInto(out *SafetyConfigSpec) {
	*out = *in
	if in.MaxToolCallsPerIteration != nil {
		in, out := &in.MaxToolCallsPerIteration, &out.MaxToolCallsPerIteration
		*out = new(int32)
		**out = **in
	}
	if in.BlockedTools != nil {
		in, out := &in.BlockedTools, &out.BlockedTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequireApprovalFor != nil {
		in, out := &in.RequireApprovalFor, &out.RequireApprovalFor
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ContentFilters != nil {
		in, out := &in.ContentFilters, &out.ContentFilters
		*out = make([]AgentContentFilterSpec, len(*in))
		copy(*out, *in)
	}
	if in.MaxCostPerExecution != nil {
		in, out := &in.MaxCostPerExecution, &out.MaxCostPerExecution
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetyConfigSpec.
func (in *SafetyConfigSpec) DeepCopy() *SafetyConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SafetyConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceReference) DeepCopyInto(out *ServiceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceReference.
func (in *ServiceReference) DeepCopy() *ServiceReference {
	if in == nil {
		return nil
	}
	out := new(ServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SynthesisInfo) DeepCopyInto(out *SynthesisInfo) {
	*out = *in
	if in.LastSynthesisTime != nil {
		in, out := &in.LastSynthesisTime, &out.LastSynthesisTime
		*out = (*in).DeepCopy()
	}
	if in.ValidationErrors != nil {
		in, out := &in.ValidationErrors, &out.ValidationErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SynthesisInfo.
func (in *SynthesisInfo) DeepCopy() *SynthesisInfo {
	if in == nil {
		return nil
	}
	out := new(SynthesisInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolFrequency) DeepCopyInto(out *ToolFrequency) {
	*out = *in
	if in.Percentage != nil {
		in, out := &in.Percentage, &out.Percentage
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolFrequency.
func (in *ToolFrequency) DeepCopy() *ToolFrequency {
	if in == nil {
		return nil
	}
	out := new(ToolFrequency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolPreferencesSpec) DeepCopyInto(out *ToolPreferencesSpec) {
	*out = *in
	if in.PreferredTools != nil {
		in, out := &in.PreferredTools, &out.PreferredTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AvoidTools != nil {
		in, out := &in.AvoidTools, &out.AvoidTools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolPreferencesSpec.
func (in *ToolPreferencesSpec) DeepCopy() *ToolPreferencesSpec {
	if in == nil {
		return nil
	}
	out := new(ToolPreferencesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolProperty) DeepCopyInto(out *ToolProperty) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolProperty.
func (in *ToolProperty) DeepCopy() *ToolProperty {
	if in == nil {
		return nil
	}
	out := new(ToolProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolReference) DeepCopyInto(out *ToolReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolReference.
func (in *ToolReference) DeepCopy() *ToolReference {
	if in == nil {
		return nil
	}
	out := new(ToolReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolSchema) DeepCopyInto(out *ToolSchema) {
	*out = *in
	if in.InputSchema != nil {
		in, out := &in.InputSchema, &out.InputSchema
		*out = new(ToolSchemaDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.OutputSchema != nil {
		in, out := &in.OutputSchema, &out.OutputSchema
		*out = new(ToolSchemaDefinition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolSchema.
func (in *ToolSchema) DeepCopy() *ToolSchema {
	if in == nil {
		return nil
	}
	out := new(ToolSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolSchemaDefinition) DeepCopyInto(out *ToolSchemaDefinition) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]ToolProperty, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolSchemaDefinition.
func (in *ToolSchemaDefinition) DeepCopy() *ToolSchemaDefinition {
	if in == nil {
		return nil
	}
	out := new(ToolSchemaDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolUsageSpec) DeepCopyInto(out *ToolUsageSpec) {
	*out = *in
	if in.AverageLatency != nil {
		in, out := &in.AverageLatency, &out.AverageLatency
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolUsageSpec.
func (in *ToolUsageSpec) DeepCopy() *ToolUsageSpec {
	if in == nil {
		return nil
	}
	out := new(ToolUsageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopicFrequency) DeepCopyInto(out *TopicFrequency) {
	*out = *in
	if in.Percentage != nil {
		in, out := &in.Percentage, &out.Percentage
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopicFrequency.
func (in *TopicFrequency) DeepCopy() *TopicFrequency {
	if in == nil {
		return nil
	}
	out := new(TopicFrequency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateStrategySpec) DeepCopyInto(out *UpdateStrategySpec) {
	*out = *in
	if in.RollingUpdate != nil {
		in, out := &in.RollingUpdate, &out.RollingUpdate
		*out = new(RollingUpdateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateStrategySpec.
func (in *UpdateStrategySpec) DeepCopy() *UpdateStrategySpec {
	if in == nil {
		return nil
	}
	out := new(UpdateStrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSpec) DeepCopyInto(out *WorkspaceSpec) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSpec.
func (in *WorkspaceSpec) DeepCopy() *WorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}
