source 'https://rubygems.org'

# Language Operator SDK - pre-installed globally, but listed here for bundler
gem 'language-operator', '= 0.1.0'

group :development, :test do
  gem 'rspec', '~> 3.13'
  gem 'webmock', '~> 3.23'
  gem 'simplecov', '~> 0.22', require: false
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-performance', '~> 1.20'
  gem 'yard', '~> 0.9.37'
end
