apiVersion: langop.io/v1alpha1
kind: LanguageModel
metadata:
  name: gpt-4-turbo
  namespace: langop-system
spec:
  # Provider type
  provider: openai

  # Model identifier
  modelName: gpt-4-turbo-preview

  # API key from Kubernetes secret
  apiKeySecretRef:
    name: openai-credentials
    key: api-key

  # Request timeout
  timeout: "5m"

  # Rate limiting
  rateLimits:
    requestsPerMinute: 100
    tokensPerMinute: 100000
    concurrentRequests: 10

  # Retry policy
  retryPolicy:
    maxAttempts: 3
    initialBackoff: "1s"
    maxBackoff: "30s"
    backoffMultiplier: 2.0
    retryableStatusCodes:
      - 429  # Rate limit
      - 500  # Internal server error
      - 502  # Bad gateway
      - 503  # Service unavailable

  # Model configuration
  configuration:
    temperature: 0.7
    maxTokens: 4096
    topP: 1.0

  # Response caching
  caching:
    enabled: true
    ttl: "5m"
    backend: memory

  # Observability
  observability:
    metrics: true
    tracing: false
    logging:
      level: info
      logRequests: true
      logResponses: false

  # Cost tracking
  costTracking:
    enabled: true
    currency: "USD"
    inputTokenCost: 0.01  # per 1000 tokens
    outputTokenCost: 0.03  # per 1000 tokens
