apiVersion: langop.io/v1alpha1
kind: LanguageTool
metadata:
  name: web-tool
  namespace: demo
spec:
  image: git.theryans.io/language-operator/web-tool:latest
  deploymentMode: sidecar
  port: 80
  egress:
  - description: Allow HTTPS to web
    to:
      dns:
      - "*.duckduckgo.com"
      - "html.duckduckgo.com"
    ports:
    - port: 443
      protocol: TCP
