source 'https://rubygems.org'

# Production dependencies
# (Inherited from based/server image)

# Development dependencies
group :development do
  gem 'rubocop', '~> 1.60'
  gem 'rubocop-performance', '~> 1.20'
  gem 'yard', '~> 0.9.37'
end
